# Cloudflare Workers configuration
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "chainfuse-auth-example"
main = "index.js"

# https://developers.cloudflare.com/workers/platform/compatibility-dates/
compatibility_date = "2022-11-30"

account_id = "e9b82b39aa91575a2643529d24a1bf02"

routes = [
  { pattern = "auth-example.chainfuse.com/*", zone_id = "e1106a13cd93f45de816417446837e9e" },
  { pattern = "auth-example-a.chainfuse.com/*", zone_id = "e1106a13cd93f45de816417446837e9e" }
]

rules = [
  { type = "ESModule", globs = ["dist/*.js"] },
  { type = "Text", globs = ["dist/*.md"], fallthrough = true }
]

[vars]
APP_ENV = "prod"
APP_NAME = "chainfuse"
APP_HOSTNAME = "auth-example.chainfuse.com"
FIREBASE_API_KEY = "AIzaSyApwYy2O33hvwo2G3OSt1Vi0TTjvW45UVU"

# [secrets]
# GOOGLE_CLOUD_CREDENTIALS

[site]
bucket = "../app/dist"

[env.test]
name = "chainfuse-auth-example-test"
