# Cloudflare Workers configuration
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "$APP_NAME-site"
main = "index.js"

# https://developers.cloudflare.com/workers/platform/compatibility-dates/
compatibility_date = "2022-11-30"

account_id = "$CLOUDFLARE_ACCOUNT_ID"

route = { pattern = "$APP_HOSTNAME/*", zone_id = "$CLOUDFLARE_ZONE_ID" }

[vars]
APP_ENV = "$APP_ENV"
APP_NAME = "$APP_NAME"
APP_HOSTNAME = "$APP_HOSTNAME"

# [secrets]
# GOOGLE_CLOUD_CREDENTIALS

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[site]
bucket = "../app"
