# GitHub Actions workflow
# https://help.github.com/actions

name: Push (release)

on:
  push:
    branches: [release]

env:
  VERSION: ${{ github.event.pull_request.number }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  HUSKY: 0

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.yarn/cache
            ${{ github.workspace }}/.yarn/unplugged
            ${{ github.workspace }}/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      # Install dependencies
      - name: yarn install
        run: |
          yarn config set enableGlobalCache false
          yarn install

      # Deploy
      # - run: yarn api:deploy --env=prod
      # - run: yarn site:deploy --env=prod
