# GitHub Actions workflow for Pull Requests
# https://help.github.com/actions

name: PR

on: [pull_request]

env:
  VERSION: ${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.yarn/cache
            ${{ github.workspace }}/.yarn/unplugged
            ${{ github.workspace }}/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      # Install dependencies
      - name: yarn install
        run: |
          yarn config set enableGlobalCache false
          yarn install

      # Analyze code for potential problems
      - run: yarn prettier --check .
      - run: yarn lint
      - run: yarn tsc

      # Test
      - run: yarn test

      # Build and deploy
      - run: yarn build
      # - run: yarn deploy --env=test
