# GitHub Actions workflow
# https://help.github.com/actions

name: PR

on: [pull_request]

env:
  VERSION: ${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      # Install dependencies
      - run: yarn install

      # Analyze code for potential problems
      - run: yarn prettier --check .
      - run: yarn lint
      - run: yarn tsc --build

      # Compile and test
      - run: yarn workspace app build
      - run: yarn workspace api build
      - run: yarn workspace edge build
      - run: yarn workspace api test
      # - run: yarn workspace edge test

      # Build and deploy
      # - run: yarn workspace api deploy --env=test --version=$VERSION
      # - run: yarn workspace edge deploy --env=test --version=$VERSION
